[2023-12-27 16:30:55,390: INFO: main: new project started]
[2023-12-27 16:31:17,323: INFO: main: new project started]
[2023-12-27 16:34:44,688: INFO: main: new project started]
[2023-12-28 12:38:40,421: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-28 12:38:40,429: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-28 12:57:53,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-28 12:57:53,484: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-28 12:57:53,486: INFO: common: created directory at: artifacts]
[2023-12-28 12:57:53,487: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-28 12:57:53,489: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1LgBuNKYtDGtb0gOhrES4qTBX7HJ4qnm6/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 12:58:05,256: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/1LgBuNKYtDGtb0gOhrES4qTBX7HJ4qnm6/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 13:03:00,004: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-28 13:03:00,007: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-28 13:03:00,009: INFO: common: created directory at: artifacts]
[2023-12-28 13:03:00,010: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-28 13:03:00,013: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1LgBuNKYtDGtb0gOhrES4qTBX7HJ4qnm6/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 13:03:15,220: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/1LgBuNKYtDGtb0gOhrES4qTBX7HJ4qnm6/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 13:16:27,971: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-28 13:16:27,979: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-28 13:16:27,980: INFO: common: created directory at: artifacts]
[2023-12-28 13:16:27,981: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-28 13:16:27,982: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 13:16:41,938: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 14:28:33,190: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-28 14:28:33,194: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-28 14:28:33,197: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-28 14:28:33,197: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "D:\tube\kidney_tumor\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jarviz_92\anaconda3\envs\kidney\Lib\site-packages\box\box.py", line 284, in __init__
    raise BoxValueError("Cannot extrapolate Box from string")
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tube\kidney_tumor\main.py", line 11, in <module>
    data_ingestion.main()
  File "D:\tube\kidney_tumor\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tube\kidney_tumor\src\cnnClassifier\config\configuration.py", line 14, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jarviz_92\anaconda3\envs\kidney\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tube\kidney_tumor\src\cnnClassifier\utils\common.py", line 37, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2023-12-28 14:30:08,868: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-28 14:30:08,870: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-28 14:30:08,879: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-28 14:30:08,880: INFO: common: created directory at: artifacts]
[2023-12-28 14:30:08,881: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-28 14:30:08,881: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1LgBuNKYtDGtb0gOhrES4qTBX7HJ4qnm6/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 14:30:09,547: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1LgBuNKYtDGtb0gOhrES4qTBX7HJ4qnm6/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 14:30:09,548: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "D:\tube\kidney_tumor\main.py", line 11, in <module>
    data_ingestion.main()
  File "D:\tube\kidney_tumor\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\data_ingestion.py", line 45, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jarviz_92\anaconda3\envs\kidney\Lib\zipfile\__init__.py", line 1321, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2023-12-28 14:36:18,724: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-28 14:36:18,732: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-28 14:36:18,735: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-28 14:36:18,736: INFO: common: created directory at: artifacts]
[2023-12-28 14:36:18,736: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-28 14:36:18,737: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 14:36:38,321: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2023-12-28 14:36:38,828: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 09:29:18,668: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 09:29:18,680: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 09:29:18,697: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 09:29:18,699: INFO: common: created directory at: artifacts]
[2024-02-04 09:29:18,700: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 09:29:18,700: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 09:29:19,452: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 09:29:19,973: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 09:36:19,818: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 09:36:19,820: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 09:36:19,821: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 09:36:19,823: INFO: common: created directory at: artifacts]
[2024-02-04 09:36:19,823: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 09:36:19,824: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 09:36:20,422: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 09:36:20,843: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 10:55:31,032: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 10:55:31,047: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 10:55:31,049: INFO: common: created directory at: artifacts]
[2024-02-04 10:55:31,051: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-04 11:15:11,836: INFO: utils: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-04 11:15:11,837: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-04 11:15:14,388: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 11:15:14,391: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 11:15:14,397: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 11:15:14,399: INFO: common: created directory at: artifacts]
[2024-02-04 11:15:14,400: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 11:15:14,402: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 11:15:15,115: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 11:15:15,117: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "d:\tube\kidney_tumor\main.py", line 12, in <module>
    data_ingestion.main()
  File "d:\tube\kidney_tumor\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "d:\tube\kidney_tumor\src\cnnClassifier\components\data_ingestion.py", line 45, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\Jarviz_92\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1249, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-02-04 12:03:36,634: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 12:03:36,638: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 12:03:36,640: INFO: common: created directory at: artifacts]
[2024-02-04 12:03:36,642: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 12:03:36,643: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 12:03:38,216: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 12:16:01,069: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 12:16:01,080: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 12:16:01,082: INFO: common: created directory at: artifacts]
[2024-02-04 12:16:01,084: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 12:16:01,085: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 12:16:02,439: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 12:17:32,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 12:17:32,600: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 12:17:32,602: INFO: common: created directory at: artifacts]
[2024-02-04 12:17:32,603: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 12:17:32,605: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 12:17:34,190: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 12:26:46,776: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 12:26:46,780: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 12:26:46,783: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 12:26:46,784: INFO: common: created directory at: artifacts]
[2024-02-04 12:26:46,785: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 12:26:46,786: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 12:27:18,593: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 12:27:18,950: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 12:27:18,951: INFO: main: *******************]
[2024-02-04 12:27:18,951: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-04 12:27:18,952: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 12:27:18,954: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 12:27:18,955: INFO: common: created directory at: artifacts]
[2024-02-04 12:27:18,955: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-04 12:27:19,497: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-04 17:45:44,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 17:45:44,883: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 17:45:44,886: INFO: common: created directory at: artifacts]
[2024-02-04 17:45:44,888: INFO: common: created directory at: artifacts\training]
[2024-02-04 17:59:29,676: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 17:59:29,681: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 17:59:29,682: INFO: common: created directory at: artifacts]
[2024-02-04 17:59:29,683: INFO: common: created directory at: artifacts\training]
[2024-02-04 18:02:18,704: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 18:02:18,710: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 18:02:18,712: INFO: common: created directory at: artifacts]
[2024-02-04 18:02:18,714: INFO: common: created directory at: artifacts\training]
[2024-02-04 18:02:36,359: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 18:02:36,363: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 18:02:36,364: INFO: common: created directory at: artifacts]
[2024-02-04 18:02:36,366: INFO: common: created directory at: artifacts\training]
[2024-02-04 18:26:21,677: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 18:26:21,686: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 18:26:21,688: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 18:26:21,688: INFO: common: created directory at: artifacts]
[2024-02-04 18:26:21,689: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 18:26:21,689: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 18:26:47,825: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 18:26:48,208: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 18:26:48,208: INFO: main: *******************]
[2024-02-04 18:26:48,209: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-04 18:26:48,211: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 18:26:48,213: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 18:26:48,214: INFO: common: created directory at: artifacts]
[2024-02-04 18:26:48,214: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-04 18:26:48,818: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-04 18:26:48,819: INFO: main: *******************]
[2024-02-04 18:26:48,819: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-04 18:26:48,820: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 18:26:48,821: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 18:26:48,822: INFO: common: created directory at: artifacts]
[2024-02-04 18:26:48,822: INFO: common: created directory at: artifacts\training]
[2024-02-04 18:26:48,823: ERROR: main: 'NoneType' object has no attribute 'updated_base_model_path']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\tube\kidney_tumor\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.get_base_model()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\model_training.py", line 16, in get_base_model
    self.config.updated_base_model_path
AttributeError: 'NoneType' object has no attribute 'updated_base_model_path'
[2024-02-04 19:02:14,805: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 19:02:14,808: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 19:02:14,812: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 19:02:14,813: INFO: common: created directory at: artifacts]
[2024-02-04 19:02:14,813: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 19:02:14,815: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 19:02:44,651: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 19:02:45,168: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 19:02:45,169: INFO: main: *******************]
[2024-02-04 19:02:45,169: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-04 19:02:45,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 19:02:45,175: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 19:02:45,178: INFO: common: created directory at: artifacts]
[2024-02-04 19:02:45,179: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-04 19:02:45,870: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-04 19:02:45,870: INFO: main: *******************]
[2024-02-04 19:02:45,871: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-04 19:02:45,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 19:02:45,875: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 19:02:45,875: INFO: common: created directory at: artifacts]
[2024-02-04 19:02:45,876: INFO: common: created directory at: artifacts\training]
[2024-02-04 19:02:45,877: ERROR: main: 'NoneType' object has no attribute 'updated_base_model_path']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\tube\kidney_tumor\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.get_base_model()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\model_training.py", line 16, in get_base_model
    self.config.updated_base_model_path
AttributeError: 'NoneType' object has no attribute 'updated_base_model_path'
[2024-02-04 19:11:44,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 19:11:44,740: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 19:11:44,746: INFO: common: created directory at: artifacts]
[2024-02-04 19:11:44,749: INFO: common: created directory at: artifacts\training]
[2024-02-04 20:27:22,809: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 20:27:22,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 20:27:22,815: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 20:27:22,816: INFO: common: created directory at: artifacts]
[2024-02-04 20:27:22,817: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 20:27:22,819: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 20:27:50,287: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 20:27:50,941: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 20:27:50,941: INFO: main: *******************]
[2024-02-04 20:27:50,942: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-04 20:27:50,944: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 20:27:50,946: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 20:27:50,946: INFO: common: created directory at: artifacts]
[2024-02-04 20:27:50,947: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-04 20:27:51,676: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-04 20:27:51,676: INFO: main: *******************]
[2024-02-04 20:27:51,676: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-04 20:27:51,678: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 20:27:51,680: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 20:27:51,681: INFO: common: created directory at: artifacts]
[2024-02-04 20:27:51,681: INFO: common: created directory at: artifacts\training]
[2024-02-04 20:27:51,681: ERROR: main: 'NoneType' object has no attribute 'updated_base_model_path']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\tube\kidney_tumor\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.get_base_model()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\model_training.py", line 16, in get_base_model
    self.config.updated_base_model_path
AttributeError: 'NoneType' object has no attribute 'updated_base_model_path'
[2024-02-04 20:45:59,517: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 20:45:59,520: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 20:45:59,526: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 20:45:59,529: INFO: common: created directory at: artifacts]
[2024-02-04 20:45:59,531: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 20:45:59,532: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 20:46:34,733: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 20:46:35,885: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 20:46:35,886: INFO: main: *******************]
[2024-02-04 20:46:35,886: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-04 20:46:35,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 20:46:35,890: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 20:46:35,891: INFO: common: created directory at: artifacts]
[2024-02-04 20:46:35,892: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-04 20:46:36,867: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-04 20:46:36,868: INFO: main: *******************]
[2024-02-04 20:46:36,868: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-04 20:46:36,870: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 20:46:36,871: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 20:46:36,878: INFO: common: created directory at: artifacts]
[2024-02-04 20:46:36,878: INFO: common: created directory at: artifacts\training]
[2024-02-04 20:46:36,879: ERROR: main: 'NoneType' object has no attribute 'updated_base_model_path']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    obj.main()
  File "D:\tube\kidney_tumor\src\cnnClassifier\pipeline\stage_03_model_training.py", line 19, in main
    training.get_base_model()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\model_training.py", line 16, in get_base_model
    self.config.updated_base_model_path
AttributeError: 'NoneType' object has no attribute 'updated_base_model_path'
[2024-02-04 20:57:04,479: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 20:57:04,486: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 20:57:04,487: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 20:57:04,488: INFO: common: created directory at: artifacts]
[2024-02-04 20:57:04,489: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 20:57:04,490: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 20:57:33,025: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 20:57:33,647: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 20:57:33,648: INFO: main: *******************]
[2024-02-04 20:57:33,648: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-04 20:57:33,651: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 20:57:33,653: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 20:57:33,654: INFO: common: created directory at: artifacts]
[2024-02-04 20:57:33,654: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-04 20:57:34,459: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-04 20:57:34,460: INFO: main: *******************]
[2024-02-04 20:57:34,460: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-04 20:57:34,465: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-04 20:57:34,467: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 20:57:34,468: INFO: common: created directory at: artifacts]
[2024-02-04 20:57:34,469: INFO: common: created directory at: artifacts\training]
[2024-02-04 20:58:43,184: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-05 18:19:51,452: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-05 18:19:51,461: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 18:19:51,462: INFO: common: created directory at: artifacts]
[2024-02-05 18:20:01,128: INFO: common: json file saved at: scores.json]
[2024-02-05 18:20:04,768: WARNING: deprecation: From c:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.]
[2024-02-05 18:20:04,777: WARNING: deprecation: From c:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.]
[2024-02-05 18:20:06,544: INFO: builder_impl: Assets written to: C:\Users\JARVIZ~1\AppData\Local\Temp\tmpbf3t5f7g\model\data\model\assets]
[2024-02-07 15:04:19,228: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-07 15:04:19,254: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 15:04:19,277: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 15:04:19,279: INFO: common: created directory at: artifacts]
[2024-02-07 15:04:19,281: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-07 15:04:19,282: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 15:04:34,125: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 15:04:35,013: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-07 15:04:35,014: INFO: main: *******************]
[2024-02-07 15:04:35,015: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-07 15:04:35,019: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 15:04:35,023: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 15:04:35,025: INFO: common: created directory at: artifacts]
[2024-02-07 15:04:35,026: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-07 15:04:36,104: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-07 15:04:36,105: INFO: main: *******************]
[2024-02-07 15:04:36,106: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-07 15:04:36,111: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 15:04:36,116: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 15:04:36,117: INFO: common: created directory at: artifacts]
[2024-02-07 15:04:36,120: INFO: common: created directory at: artifacts\training]
[2024-02-07 15:05:56,010: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-07 15:05:56,010: INFO: main: *******************]
[2024-02-07 15:05:56,011: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<]
[2024-02-07 15:05:56,014: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 15:05:56,017: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 15:05:56,017: INFO: common: created directory at: artifacts]
[2024-02-07 15:06:11,454: INFO: common: json file saved at: scores.json]
[2024-02-07 15:06:14,141: WARNING: deprecation: From C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.]
[2024-02-07 15:06:14,150: WARNING: deprecation: From C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.]
[2024-02-07 15:06:16,153: INFO: builder_impl: Assets written to: C:\Users\JARVIZ~1\AppData\Local\Temp\tmp9hn4vunx\model\data\model\assets]
[2024-02-07 15:07:11,259: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
[2024-02-07 15:07:58,666: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-07 15:07:58,670: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 15:07:58,685: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 15:07:58,686: INFO: common: created directory at: artifacts]
[2024-02-07 15:07:58,687: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-07 15:07:58,688: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 15:08:13,639: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 15:08:15,602: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-07 15:08:15,602: INFO: main: *******************]
[2024-02-07 15:08:15,603: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-07 15:08:15,608: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 15:08:15,612: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 15:08:15,613: INFO: common: created directory at: artifacts]
[2024-02-07 15:08:15,614: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-07 15:08:18,969: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-07 15:08:18,970: INFO: main: *******************]
[2024-02-07 15:08:18,970: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-07 15:08:18,976: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 15:08:18,980: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 15:08:18,981: INFO: common: created directory at: artifacts]
[2024-02-07 15:08:18,982: INFO: common: created directory at: artifacts\training]
[2024-02-07 15:13:38,894: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-07 15:13:38,894: INFO: main: *******************]
[2024-02-07 15:13:38,894: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<]
[2024-02-07 15:13:38,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 15:13:38,905: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 15:13:38,907: INFO: common: created directory at: artifacts]
[2024-02-07 15:14:00,209: INFO: common: json file saved at: scores.json]
[2024-02-07 15:14:04,215: WARNING: deprecation: From C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.]
[2024-02-07 15:14:04,225: WARNING: deprecation: From C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.]
[2024-02-07 15:14:06,666: INFO: builder_impl: Assets written to: C:\Users\JARVIZ~1\AppData\Local\Temp\tmpnue4z11l\model\data\model\assets]
[2024-02-07 15:15:22,263: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
[2024-02-07 19:39:27,144: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-07 19:39:27,147: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 19:39:27,148: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 19:39:27,149: INFO: common: created directory at: artifacts]
[2024-02-07 19:39:27,150: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-07 19:39:27,150: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 19:39:54,056: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 19:39:54,523: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-07 19:39:54,523: INFO: main: *******************]
[2024-02-07 19:39:54,523: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-07 19:39:54,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 19:39:54,526: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 19:39:54,527: INFO: common: created directory at: artifacts]
[2024-02-07 19:39:54,528: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-07 19:39:55,094: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-07 19:39:55,095: INFO: main: *******************]
[2024-02-07 19:39:55,095: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-07 19:39:55,097: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 19:39:55,098: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 19:39:55,099: INFO: common: created directory at: artifacts]
[2024-02-07 19:39:55,100: INFO: common: created directory at: artifacts\training]
[2024-02-07 19:39:55,326: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    obj.main()
  File "D:\tube\kidney_tumor\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\model_training.py", line 36, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\keras\preprocessing\image.py", line 943, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\keras\preprocessing\image.py", line 381, in __init__
    super(DirectoryIterator, self).__init__(
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\keras_preprocessing\image\directory_iterator.py", line 115, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-02-07 19:56:53,430: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-07 19:56:53,432: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 19:56:53,433: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 19:56:53,434: INFO: common: created directory at: artifacts]
[2024-02-07 19:56:53,434: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-07 19:56:53,434: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 19:57:08,492: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 19:57:09,131: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-07 19:58:08,743: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-07 19:58:08,744: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 19:58:08,746: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 19:58:08,746: INFO: common: created directory at: artifacts]
[2024-02-07 19:58:08,747: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-07 19:58:08,747: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 19:58:22,717: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 19:58:23,157: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-07 20:01:20,238: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-07 20:01:20,241: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 20:01:20,244: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 20:01:20,244: INFO: common: created directory at: artifacts]
[2024-02-07 20:01:20,245: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-07 20:01:20,246: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 20:01:34,159: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 20:01:34,727: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-07 20:06:07,259: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-07 20:06:07,261: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 20:06:07,262: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 20:06:07,263: INFO: common: created directory at: artifacts]
[2024-02-07 20:06:07,263: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-07 20:06:07,264: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 20:06:22,816: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/15vjajBNnvo1EkAghZEYZn-tOwmGnTkzx/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 20:06:23,215: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-07 20:23:29,460: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-07 20:23:29,462: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 20:23:29,464: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 20:23:29,464: INFO: common: created directory at: artifacts]
[2024-02-07 20:23:29,464: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-07 20:23:29,465: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1USd73t7yYMEebRXkKY_4NyXz2Re0U8_A/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-07 20:23:46,149: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1USd73t7yYMEebRXkKY_4NyXz2Re0U8_A/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-07 20:23:46,559: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-07 20:23:50,418: INFO: stage_02_prepare_base_model: *******************]
[2024-02-07 20:23:50,418: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-07 20:23:50,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 20:23:50,422: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 20:23:50,425: INFO: common: created directory at: artifacts]
[2024-02-07 20:23:50,427: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-07 20:23:50,902: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-07 20:23:54,975: INFO: stage_03_model_training: *******************]
[2024-02-07 20:23:54,977: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-02-07 20:23:54,979: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 20:23:54,981: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 20:23:54,981: INFO: common: created directory at: artifacts]
[2024-02-07 20:23:54,982: INFO: common: created directory at: artifacts\training]
[2024-02-07 20:23:55,217: ERROR: stage_03_model_training: Asked to retrieve element 0, but the Sequence has length 0]
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_03_model_training.py", line 35, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_03_model_training.py", line 26, in main
    training.train()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\model_training.py", line 74, in train
    self.model.fit(
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1049, in fit
    data_handler = data_adapter.DataHandler(
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1105, in __init__
    self._adapter = adapter_cls(
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 909, in __init__
    super(KerasSequenceAdapter, self).__init__(
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 786, in __init__
    peek, x = self._peek_and_restore(x)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 920, in _peek_and_restore
    return x[0], x
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\keras_preprocessing\image\iterator.py", line 54, in __getitem__
    raise ValueError('Asked to retrieve element {idx}, '
ValueError: Asked to retrieve element 0, but the Sequence has length 0
[2024-02-07 20:57:04,804: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-07 20:57:04,806: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 20:57:04,807: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 20:57:04,807: INFO: common: created directory at: artifacts]
[2024-02-07 20:57:04,807: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-07 20:57:04,808: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1D7QlbGpmlro9bvCJagWr6vcMX7cw7cEU/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 20:57:21,891: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1D7QlbGpmlro9bvCJagWr6vcMX7cw7cEU/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-07 20:57:22,273: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-07 20:57:33,106: INFO: stage_02_prepare_base_model: *******************]
[2024-02-07 20:57:33,106: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-07 20:57:33,108: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 20:57:33,109: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 20:57:33,109: INFO: common: created directory at: artifacts]
[2024-02-07 20:57:33,110: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-07 20:57:33,593: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-07 20:57:38,781: INFO: stage_03_model_training: *******************]
[2024-02-07 20:57:38,807: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-02-07 20:57:38,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 20:57:38,813: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 20:57:38,814: INFO: common: created directory at: artifacts]
[2024-02-07 20:57:38,815: INFO: common: created directory at: artifacts\training]
[2024-02-07 21:00:14,547: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-07 21:03:43,540: INFO: stage_04_model_evaluation_ml_flow: *******************]
[2024-02-07 21:03:43,540: INFO: stage_04_model_evaluation_ml_flow: >>>>>> stage model evaluation stages started <<<<<<]
[2024-02-07 21:03:43,542: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 21:03:43,543: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 21:03:43,543: INFO: common: created directory at: artifacts]
[2024-02-07 21:03:51,427: INFO: common: json file saved at: scores.json]
[2024-02-07 21:03:51,427: INFO: stage_04_model_evaluation_ml_flow: >>>>>> stage model evaluation stages completed <<<<<<

x==========x]
[2024-02-07 21:17:50,508: INFO: stage_04_model_evaluation_ml_flow: *******************]
[2024-02-07 21:17:50,508: INFO: stage_04_model_evaluation_ml_flow: >>>>>> stage model evaluation stages started <<<<<<]
[2024-02-07 21:17:50,510: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 21:17:50,511: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 21:17:50,512: INFO: common: created directory at: artifacts]
[2024-02-07 21:17:58,618: INFO: common: json file saved at: scores.json]
[2024-02-07 21:17:58,619: ERROR: stage_04_model_evaluation_ml_flow: [WinError 3] The system cannot find the path specified: 'S:\\']
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation_ml_flow.py", line 27, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation_ml_flow.py", line 20, in main
    evaluation.log_into_mlflow()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\model_evaluation_ml_flow.py", line 59, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\fluent.py", line 308, in start_run
    client = MlflowClient()
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\client.py", line 93, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 52, in __init__
    self.store
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 56, in store
    return utils._get_store(self.tracking_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\utils.py", line 216, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\utils.py", line 130, in _get_file_store
    return FileStore(store_uri, store_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\store\tracking\file_store.py", line 172, in __init__
    self._create_default_experiment()
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\store\tracking\file_store.py", line 178, in _create_default_experiment
    mkdir(self.root_directory)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\utils\file_utils.py", line 212, in mkdir
    raise e
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\utils\file_utils.py", line 209, in mkdir
    os.makedirs(target)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'S:\\'
[2024-02-07 21:21:53,744: INFO: stage_04_model_evaluation_ml_flow: *******************]
[2024-02-07 21:21:53,745: INFO: stage_04_model_evaluation_ml_flow: >>>>>> stage model evaluation stages started <<<<<<]
[2024-02-07 21:21:53,746: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 21:21:53,748: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 21:21:53,748: INFO: common: created directory at: artifacts]
[2024-02-07 21:22:01,695: INFO: common: json file saved at: scores.json]
[2024-02-07 21:22:01,696: ERROR: stage_04_model_evaluation_ml_flow: [WinError 3] The system cannot find the path specified: 'S:\\']
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation_ml_flow.py", line 27, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation_ml_flow.py", line 20, in main
    evaluation.log_into_mlflow()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\model_evaluation_ml_flow.py", line 59, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\fluent.py", line 308, in start_run
    client = MlflowClient()
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\client.py", line 93, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 52, in __init__
    self.store
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 56, in store
    return utils._get_store(self.tracking_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\utils.py", line 216, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\utils.py", line 130, in _get_file_store
    return FileStore(store_uri, store_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\store\tracking\file_store.py", line 172, in __init__
    self._create_default_experiment()
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\store\tracking\file_store.py", line 178, in _create_default_experiment
    mkdir(self.root_directory)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\utils\file_utils.py", line 212, in mkdir
    raise e
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\utils\file_utils.py", line 209, in mkdir
    os.makedirs(target)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'S:\\'
[2024-02-07 21:23:15,276: INFO: stage_04_model_evaluation_ml_flow: *******************]
[2024-02-07 21:23:15,276: INFO: stage_04_model_evaluation_ml_flow: >>>>>> stage model evaluation stages started <<<<<<]
[2024-02-07 21:23:15,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 21:23:15,279: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 21:23:15,279: INFO: common: created directory at: artifacts]
[2024-02-07 21:23:23,127: INFO: common: json file saved at: scores.json]
[2024-02-07 21:23:23,127: ERROR: stage_04_model_evaluation_ml_flow: [WinError 3] The system cannot find the path specified: 'S:\\']
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation_ml_flow.py", line 27, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation_ml_flow.py", line 20, in main
    evaluation.log_into_mlflow()
  File "D:\tube\kidney_tumor\src\cnnClassifier\components\model_evaluation_ml_flow.py", line 59, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\fluent.py", line 308, in start_run
    client = MlflowClient()
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\client.py", line 93, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 52, in __init__
    self.store
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 56, in store
    return utils._get_store(self.tracking_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\utils.py", line 216, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\tracking\_tracking_service\utils.py", line 130, in _get_file_store
    return FileStore(store_uri, store_uri)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\store\tracking\file_store.py", line 172, in __init__
    self._create_default_experiment()
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\store\tracking\file_store.py", line 178, in _create_default_experiment
    mkdir(self.root_directory)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\utils\file_utils.py", line 212, in mkdir
    raise e
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\mlflow\utils\file_utils.py", line 209, in mkdir
    os.makedirs(target)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jarviz_92\anaconda3\envs\chick\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'S:\\'
[2024-02-07 21:25:15,581: INFO: stage_04_model_evaluation_ml_flow: *******************]
[2024-02-07 21:25:15,581: INFO: stage_04_model_evaluation_ml_flow: >>>>>> stage model evaluation stages started <<<<<<]
[2024-02-07 21:25:15,583: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-07 21:25:15,585: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 21:25:15,586: INFO: common: created directory at: artifacts]
[2024-02-07 21:25:23,730: INFO: common: json file saved at: scores.json]
[2024-02-07 21:25:26,075: WARNING: deprecation: From C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.]
[2024-02-07 21:25:26,080: WARNING: deprecation: From C:\Users\Jarviz_92\anaconda3\envs\chick\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.]
[2024-02-07 21:25:27,648: INFO: builder_impl: Assets written to: C:\Users\JARVIZ~1\AppData\Local\Temp\tmpbqs23ais\model\data\model\assets]
[2024-02-07 21:26:10,502: INFO: stage_04_model_evaluation_ml_flow: >>>>>> stage model evaluation stages completed <<<<<<

x==========x]
